module.exports = {
  apps: [
    {
      name: "thepiolo-web",
      script: "npm",
      args: "start",
      cwd: process.env.PROJECT_DIR || "/home/admin_dany/thepiolo_web",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        NODE_OPTIONS: "--max-old-space-size=512",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "800M",
      kill_timeout: 5000,
      error_file: "./logs/pm2-error.log",
      out_file: "./logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "30s",
      restart_delay: 4000,
      listen_timeout: 10000,
      shutdown_with_message: true,
      env_production: {
        NODE_ENV: "production",
        PORT: 3001,
        NODE_OPTIONS: "--max-old-space-size=512",
      },
    },
  ],
};
